-- Generated by Oracle SQL Developer Data Modeler 4.0.0.833
--   at:        2014-06-13 20:42:28 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE Godziny_przyjec
  (
    typ         CHAR (1)  ,
    dzien_tyg   INTEGER  ,
    od          VARCHAR2(10),
    do          VARCHAR2(10),
    placowka_id INTEGER 
  ) ;
ALTER TABLE Godziny_przyjec ADD CONSTRAINT Godziny_przyjec_PK PRIMARY KEY ( placowka_id ) ;

CREATE TABLE Lekarz
  (
    id          INTEGER  ,
    imie        VARCHAR2 (20 CHAR)  ,
    imie2       VARCHAR2 (20 CHAR) ,
    nazwisko    VARCHAR2 (20 CHAR)  ,
    tytul       VARCHAR2 (20 CHAR) ,
    placowka_id INTEGER 
  ) ;
CREATE INDEX Lekarz__IDX ON Lekarz
  ( nazwisko ASC
  ) ;
ALTER TABLE Lekarz ADD CONSTRAINT Lekarz_PK PRIMARY KEY ( id ) ;

CREATE TABLE Pacjent
  (
    id       INTEGER  ,
    imie     VARCHAR2 (20 CHAR)  ,
    imie2    VARCHAR2 (20 CHAR) ,
    nazwisko VARCHAR2 (20)  ,
    pesel    INTEGER  ,
    adres VARCHAR2(100)  ,
    nr_tel    INTEGER  ,
    Pakiet_id INTEGER  ,
    dolaczyl  DATE 
  ) ;
CREATE INDEX Pacjent__IDX ON Pacjent
  ( pesel ASC
  ) ;
ALTER TABLE Pacjent ADD CONSTRAINT Pacjent_PK PRIMARY KEY ( id ) ;
ALTER TABLE Pacjent ADD CONSTRAINT Pacjent__UN UNIQUE ( pesel ) ;

CREATE TABLE Pakiet
  (
    id     INTEGER  ,
    nazwa  VARCHAR2 (20 CHAR)  ,
    znizka INTEGER 
  ) ;
ALTER TABLE Pakiet ADD CONSTRAINT Pakiet_PK PRIMARY KEY ( id ) ;

CREATE TABLE Placowka
  (
    id     INTEGER  ,
    nazwa  VARCHAR2 (20)  ,
    nr_tel INTEGER  ,
    adres VARCHAR2(100) 
  ) ;
ALTER TABLE Placowka ADD CONSTRAINT Placowka_PK PRIMARY KEY ( id ) ;

CREATE TABLE Spec_Lek
  (
    Specjalizacja_id INTEGER  ,
    Lekarz_id        INTEGER 
  ) ;
ALTER TABLE Spec_Lek ADD CONSTRAINT Relation_9__IDX PRIMARY KEY ( Specjalizacja_id, Lekarz_id ) ;

CREATE TABLE Specjalizacja
  ( id INTEGER  , nazwa VARCHAR2 
  ) ;
ALTER TABLE Specjalizacja ADD CONSTRAINT Specjalizacja_PK PRIMARY KEY ( id ) ;

CREATE TABLE Terminarz
  (
    gabinet   VARCHAR2 (20)  ,
    termin    DATE  ,
    od        DATE  ,
    DO        DATE  ,
    Lekarz_id INTEGER 
  ) ;
ALTER TABLE Terminarz ADD CONSTRAINT Terminarz_PK PRIMARY KEY ( Lekarz_id ) ;

CREATE TABLE Wizyta
  (
    id         INTEGER  ,
    termin     DATE  ,
    status     INTEGER  ,
    nazwa      VARCHAR2 (20 CHAR) ,
    koszt      INTEGER ,
    typ        INTEGER  ,
    Lekarz_id  INTEGER  ,
    Pacjent_id INTEGER 
  ) ;
CREATE INDEX Wizyta__IDX ON Wizyta
  ( termin ASC
  ) ;
ALTER TABLE Wizyta ADD CONSTRAINT Wizyta_PK PRIMARY KEY ( id ) ;

ALTER TABLE Spec_Lek ADD CONSTRAINT FK_ASS_10 FOREIGN KEY ( Specjalizacja_id ) REFERENCES Specjalizacja ( id ) ;

ALTER TABLE Spec_Lek ADD CONSTRAINT FK_ASS_11 FOREIGN KEY ( Lekarz_id ) REFERENCES Lekarz ( id ) ;

ALTER TABLE Godziny_przyjec ADD CONSTRAINT Godziny_przyjec_Placowka_FK FOREIGN KEY ( placowka_id ) REFERENCES Placowka ( id ) ON
DELETE CASCADE ;

ALTER TABLE Lekarz ADD CONSTRAINT Lekarz_Placowka_FK FOREIGN KEY ( placowka_id ) REFERENCES Placowka ( id ) ;

ALTER TABLE Pacjent ADD CONSTRAINT Pacjent_Pakiet_FK FOREIGN KEY ( Pakiet_id ) REFERENCES Pakiet ( id ) ;

ALTER TABLE Terminarz ADD CONSTRAINT Terminarz_Lekarz_FK FOREIGN KEY ( Lekarz_id ) REFERENCES Lekarz ( id ) ON
DELETE CASCADE ;

ALTER TABLE Wizyta ADD CONSTRAINT Wizyta_Lekarz_FK FOREIGN KEY ( Lekarz_id ) REFERENCES Lekarz ( id ) ;

ALTER TABLE Wizyta ADD CONSTRAINT Wizyta_Pacjent_FK FOREIGN KEY ( Pacjent_id ) REFERENCES Pacjent ( id ) ;

CREATE TABLE Specjalizacja
  ( id INTEGER, nazwa VARCHAR2(256)
  ) ;  2    3  

Table created.

ALTER TABLE Specjalizacja ADD CONSTRAINT Specjalizacja_PK PRIMARY KEY ( id ) ;


--CREATE SEQUENCE specjalizacja_seq;
--CREATE OR REPLACE TRIGGER specjalizacja_trig
--BEFORE INSERT ON specjalizacja
--FOR EACH ROW
--
--BEGIN
--  SELECT specjalizacja_seq.NEXTVAL
--  INTO   :new.id
--  FROM   dual;
--END;
--/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             3
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
